### PR TITLE
Rspec Testing Of Enumerable Methods Project

### PR DESCRIPTION
**Pull request by RyelBanfield**
Thi PR contains the RSpec testing for the Enumerable Methods Project.

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @RyelBanfield and @Arinpe :wave: 

You've done well so far :+1:  and I commend you for that :clap: 

However, I can not run rspec in this environment, except I first install the 'RSpec gem'

Kindly add Gemfile to the root of your directory to allow users without Rspec to run bundle install.

Do this and submit for another review 🙏

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by RyelBanfield** [comment]
Appreciate the explanation.

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi team!
Thank you for making the changes requested by the last reviewer:clap::clap:.**

**Major highlights**

- The spec for each method is clearly wrapped in one describe block
- There's one 'it' block for each expected behavior.
- The tests are clearly written and the codebase is clean.

However, we still need to make a few changes to get this project approved:muscle:.

- [x] Rename the testing.rb to testing_spec.rb. This will enable the tests to run when we run `rspec`

- [ ] The .rubocop.yml config is currently modified. See [screen-shot](https://imgur.com/a/EP6hu0a) for reference. Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. You can use this [link](https://github.com/microverseinc/linters-config/tree/master/ruby) to get a new config.

- [ ] Add more negative tests cases.

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond
Happy hacking:blush:
Eric Enaburekhan

**Review by mke2111 — APPROVED** [review]
# **🎉 STATUS: APPROVED 🎉** 

## Hey @RyelBanfield & @Arinpe, 👋🏽 
 **Congratulations 🥳 🥂 . The tests cover a wide scenario base.**

**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Pull request merged**
